### ISSUE TITLE
Users are failing to download the .Desktop folder when installing with the install script

### ISSUE THREAD

**Issue by DavidDeSimone** [DavidDeSimone/OpenCloudSaves#50]
I've received several reports of users failing to download the .Desktop file when running the installer.

I think that the fix for this will be to just distribute via the Discover store.

**Comment by tioalexis** [comment]
Can confirm that the install script fails on Steam Deck but downloading the .flatpak and installing it using Discover worked just fine.

**Comment by DavidDeSimone** [comment]
Now we are listed on flathub, so this shouldn't be an issue.
