### ISSUE TITLE
Save files uploaded but not downloaded to Deck

### ISSUE THREAD

**Issue by tioalexis** [DavidDeSimone/OpenCloudSaves#51]
**Describe the bug**
After setting up the save directory of a Prism Launcher instance, the save data gets uploaded. However when I do the same setup on the deck and try to sync, the folder remains empty. When I attempt to sync the game, the app reports "no changes", implying that it _thinks_ the files are there but when you open the directory in the file explorer the directory is empty.

**To Reproduce**
1. Install Prism Launcher. Create a Minecraft instance.
2. In Prism Launcher, select your instance and click Edit -> Worlds -> Open Folder.
3. Add this path to OpenCloudSaves.
4. Do the same for your Steam Deck.
5. From your desktop PC, sync your files so it uploads the save data to cloud.
6. Check your cloud backup and see that the files are uploaded.
7. From your Steam Deck, sync your files so it downloads the save data from the cloud.
8. It will report that there are things to download. Accept and wait for it to finish.
9. Open the directory where the save data is supposed to go.
10. The directory will be empty.
11. Sync again and it will report that there are no changes.

**Expected behavior**
Save data appears in the specified directory.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Steam Deck OS
 - Version: Whatever the latest is

**Additional context**
In my case, directory for the save data in my Steam Deck is `home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Yoru/.minecraft/saves`

**Comment by DavidDeSimone** [comment]
Thanks for the report. I'll target this for 0.17.

**Comment by DavidDeSimone** [comment]
This should be fixed in 0.17.4
