### ISSUE TITLE
Cloud Saves unsuccessful for Jedi Fallen Order, requires manual input for each save

### ISSUE THREAD

**Issue by Lilikura** [DavidDeSimone/OpenCloudSaves#52]
### Describe the issue
Each time I try to make a backup of my steam deck files for Jedi: Fallen Order it works exactly once, then creates a new folder inside the parent directory that it uses for subsequent attempts, as this folder is not the game directory, files are not affected by the game program and syncing does not happen.

### Steps to reproduce
+ Create a new entry titled Star Wars Jedi: Fallen Order
+ Set Linux Path to `/home/deck/.local/share/Steam/steamapps/compatdata/1172380/pfx/drive_c/users/steamuser/Saved Games/Respawn/JediFallenOrder`
+ Click Save
+ Sync
+ Observe a new folder in `/home/deck/.local/share/Steam/steamapps/compatdata/1172380/pfx/drive_c/users/steamuser/Saved Games/Respawn/JediFallenOrderdrive_c` now exists containing the local save files. These files are untouched by the game.

**Comment by DavidDeSimone** [comment]
Thank you for the report, I will target this for 0.17

**Comment by Lilikura** [comment]
Oh, for anyone who is viewing this in the meantime before 0.17:

The workaround I've settled upon is going up to the Respawn folder and creating a symbolic link pointing `JediFallenOrderdrive_c` to `JediFallenOrder`

**Comment by DavidDeSimone** [comment]
Keeping this open until 0.17 is released, but the work is complete.

**Comment by DavidDeSimone** [comment]
Let me know if this issue persists.
