### ISSUE TITLE
Requires the runtime org.gnome.Platform/x86_64/42 when SteamDeck is already updated to /43

### ISSUE THREAD

**Issue by sangowen** [DavidDeSimone/OpenCloudSaves#61]
Recently discover store pushes the update to org.gnome.Platform/x86_64/43, which breaks the installation process:

`error: The application io.github.daviddesimone.opencloudsaves/x86_64/master requires the runtime org.gnome.Platform/x86_64/42 which was not found`

**Comment by DavidDeSimone** [comment]
Thanks for the report - I'll target this for 0.17

**Comment by DavidDeSimone** [comment]
Update: this will be fixed in 0.17

I'm awaiting approval for being listed on flathub. It's taking a little longer than I expected, so I think I'll post a new flatpak release on GH this weekend so that people affected by this can still use the app on Linux
