### ISSUE TITLE
NextCloud storage option doesn't work

### ISSUE THREAD

**Issue by chasx003** [DavidDeSimone/OpenCloudSaves#66]
**Describe the bug**
When trying to use NextCloud as a storage option, No login/configuration window pops up, and the applications acts like it has configured the provider

**To Reproduce**
1. Fresh install OpenCloudSave
2. Click Select Cloud
3. Choose NextCloud
4. No configuration takes place

**Expected behavior**
NextCloud should have a popup for configuration, or oauth like Gdrive/Box, etc

**Desktop (please complete the following information):**
 - OS: Linux(steamdeck) and Windows 10
 - Version : v0.17.4

**Comment by DavidDeSimone** [comment]
Will try to repel and target for 0.18

**Comment by DavidDeSimone** [comment]
0.18 is going to take longer than I wanted as I polish some UI features, so I snuck this out as a new minor release 0.17.7. Please let me know if you have any issues with the new release.
