### ISSUE TITLE
Create Option to follow symlinks (Needed for EmuDeck default install)

### ISSUE THREAD

**Issue by chasx003** [DavidDeSimone/OpenCloudSaves#67]
**Is your feature request related to a problem? Please describe.**
Add an option to support following symlinks via rclone   ( -L, --copy-links    ).  Emudeck currently has a parent "save" folder that just contains symlinks to the other emulator's save folders.

**Describe the solution you'd like**
Either a checkbox for adding symlink options when adding custom games, or a text box to pass custom args to rclone

**Comment by DavidDeSimone** [comment]
Good callout - will add to v0.18 

I like both options for an rclone custom flags box, along with a control option for specifying -L

**Comment by DavidDeSimone** [comment]
I snuck this into 0.17.7, closing as fixed. Please let me know if you have any issues.
