### ISSUE TITLE
Steam Deck: Error while performing dry-run of sync

### ISSUE THREAD

**Issue by dc-grimm** [DavidDeSimone/OpenCloudSaves#78]
First of all, I had trouble originally trying to install via the install.desktop download but managed to install from the Discover store.

I configured to sync to google cloud and when attempting to sync I get the following:

```
Error while performing dry-run of sync: ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Error: unknown command "undefined" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

2023/03/08 15:50:07 Fatal error: unknown command "undefined" for "rclone"
```

**Comment by DavidDeSimone** [comment]
Hello,

We are moving away from Install.Desktop and are moving to the discover store. We are no longer offering Install.Desktop for 0.17.7, so it is good that you downloaded from the Discover Store.

I will try to repro this - was this on the steam deck (it looks like it was)? If so, was this in Desktop or Game mode?

**Comment by DavidDeSimone** [comment]
Follow up - I am unable to repro this locally. It looks like something is going wrong in our layer that is pushing rclone flags to the sync layer. 

Can you upload your log file? It is located in 'Home/.var/app/io.github.daviddesimone/opencloudsaves/cache/opencloudsaves.log'

**Comment by DavidDeSimone** [comment]
I see what is going on - I'll get a hot fix out today. In the mean time, if you open up the game you are trying to sync in the edit menu (hit the Edit button next to sync), delete the "undefined" in the Rclone flags field near the bottom.

**Comment by DavidDeSimone** [comment]
0.17.8 is out with the fix - it might take a fix minutes to propagate on flathub, but you should be able to update from the Discover Store.

**Comment by dc-grimm** [comment]
I just checked before work and it was still giving the second part.

Error: unknown command "undefined" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

I will check again after work and send you the log file.

**Comment by dc-grimm** [comment]
Your theory was indeed correct. Its working now!

Thank you for assisting and for making this application!
