### ISSUE TITLE
Steam deck gaming mode not support

### ISSUE THREAD

**Issue by partytoni** [DavidDeSimone/OpenCloudSaves#81]
**Describe the bug**
It is not possible to open the flatpak version of the application from gaming mode on steam deck. It instantly closes as soon as i press "Play"

**Desktop (please complete the following information):**
 - OS: Steam OS
 - Version 3.4.4

**Comment by DavidDeSimone** [comment]
I am unable to repro this on the deck on SteamOS version 3.4.4 - I am able to launch the game fine from Game Mode. Are you able to launch the app from Desktop mode? Are you able to upload the log file located at -> `$HOME/.var/app/io.github.daviddesimone/opencloudsaves/cache/opencloudsaves.log`

**Comment by partytoni** [comment]
It seems like a simple reboot made the job. After rebooting Steam performed some updates and now it's working correctly, I don't know why. 
Thank you for developing such a great app! If it's not a big issue you could also add Megasync to the cloud providers.

**Comment by DavidDeSimone** [comment]
Awesome, glad to hear that your issue is resolved! I'll look into Megasync.
