### ISSUE TITLE
Windows installer does not inform user the app is installed successfully, and does not create a shortcut

### ISSUE THREAD

**Issue by tioalexis** [DavidDeSimone/OpenCloudSaves#84]
**Describe the bug**
When you run the installer, it will simply say "Please wait while Windows configures Open Cloud Save". After a few seconds, it will disappear and nothing happens.

**To Reproduce**
1. Download the *.msi file from the releases tab (in this case, I am using 0.17.8)
2. Double-click the downloaded file.

**Expected behavior**
- The app is installed and appears when you search for "Open Cloud Save" in the start menu.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 22H2 (build 19045.2604)

**Additional context**
Alternatively, there should be a portable zip version where no installation is needed.

**Comment by DavidDeSimone** [comment]
I am unable to reproduce this - the MSI is installing the file for my system.

Is there anything located in `C:\Program Files\OpenCloudSaves`? 

I don't think we are properly registering in the start menu, or creating a desktop icon, which I would consider less a bug and just a really bad end user experience.

-----

The issue with a zip is that we are dependent on https://developer.microsoft.com/en-us/microsoft-edge/webview2/ which needs to be installed on the end users system prior to first launch.

**Comment by tioalexis** [comment]
I checked the directory and it seems to be installing the app correctly. The bug-like behaviour still persists though which might lead other to think the installer didn't do anything.

**Comment by DavidDeSimone** [comment]
> I checked the directory and it seems to be installing the app correctly. The bug-like behaviour still persists though which might lead other to think the installer didn't do anything.

Thanks for the report - I will add this to the list for 0.18. I agree that making this a smooth experience will be essential for windows users.

**Comment by DavidDeSimone** [comment]
0.18 should have a MUCH better user experience. I am about to put up a PR:

Now we will have a polished installer that will allow for custom install locations:

![image](https://user-images.githubusercontent.com/7245174/224464537-80b4651e-46d3-4c65-82e1-bf8fcfa7796a.png)

The finished screen will display an option to launch right away:

![image](https://user-images.githubusercontent.com/7245174/224464393-002924d8-dd26-4ed3-a770-6a3e2d194381.png)


Relaunching the MSI will give a repair/uninstall promot:

![image](https://user-images.githubusercontent.com/7245174/224464341-24af0ee9-2f1c-4699-9590-31689e22f911.png)

We will create a start menu shortcut and desktop shortcut:

![Screenshot 2023-03-10 201304](https://user-images.githubusercontent.com/7245174/224464415-5ca33a4e-8899-40fb-ab3a-bf37ddb92081.png)
